# Generated by Django 3.1.5 on 2021-11-30 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0002_userform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Useri',
        ),
    ]
