# Generated by Django 3.1.5 on 2021-12-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0003_auto_20211130_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ownerform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownername', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('ownerpin', models.PositiveIntegerField(default=0)),
                ('housecategory', models.CharField(max_length=100)),
                ('housename', models.CharField(max_length=100)),
                ('division', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chattogram', 'Chattogram'), (' Khulna', ' Khulna'), ('Barishal', 'Barishal'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh')], max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('housesize', models.CharField(max_length=100)),
                ('bedroom', models.PositiveIntegerField(default=0)),
                ('dinning', models.PositiveIntegerField(default=0)),
                ('drawing', models.PositiveIntegerField(default=0)),
                ('bathroom', models.PositiveIntegerField(default=0)),
                ('kitchen', models.PositiveIntegerField(default=0)),
                ('balcony', models.PositiveIntegerField(default=0)),
                ('housedetail', models.CharField(max_length=100)),
                ('myimg', models.ImageField(blank=True, upload_to='my')),
                ('img', models.FileField(blank=True, upload_to='doc')),
            ],
        ),
    ]
