# Generated by Django 3.1.5 on 2021-12-03 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0004_ownerform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerform',
            name='img',
        ),
        migrations.RemoveField(
            model_name='ownerform',
            name='myimg',
        ),
    ]
