# Generated by Django 3.1.5 on 2021-12-03 10:19

from django.db import migrations, models
import final.models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0005_auto_20211203_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerform',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=final.models.filepath),
        ),
    ]
