# Generated by Django 3.1.5 on 2021-12-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0006_ownerform_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerform',
            name='houserent',
            field=models.CharField(default='', max_length=100),
        ),
    ]
