# Generated by Django 3.1.5 on 2021-12-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0007_ownerform_houserent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerform',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='filepath/'),
        ),
    ]
