# Generated by Django 3.1.5 on 2021-12-04 12:43

from django.db import migrations, models
import final.models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0008_auto_20211204_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=final.models.file)),
            ],
        ),
        migrations.AlterField(
            model_name='ownerform',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=final.models.filepath),
        ),
    ]
