# Generated by Django 3.1.5 on 2021-12-05 02:24

from django.db import migrations, models
import final.models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0009_auto_20211204_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='ownerformfill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownername', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('ownerpin', models.PositiveIntegerField(default=0)),
                ('housecategory', models.CharField(max_length=100)),
                ('housename', models.CharField(max_length=100)),
                ('houserent', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to=final.models.fileimg)),
                ('division', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chattogram', 'Chattogram'), (' Khulna', ' Khulna'), ('Barishal', 'Barishal'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh')], max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('housesize', models.CharField(max_length=100)),
                ('bedroom', models.PositiveIntegerField(default=0)),
                ('dinning', models.PositiveIntegerField(default=0)),
                ('drawing', models.PositiveIntegerField(default=0)),
                ('bathroom', models.PositiveIntegerField(default=0)),
                ('kitchen', models.PositiveIntegerField(default=0)),
                ('balcony', models.PositiveIntegerField(default=0)),
                ('housedetail', models.CharField(max_length=100)),
            ],
        ),
    ]
