# Generated by Django 3.1.5 on 2021-12-05 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0010_ownerformfill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownerformfill',
            old_name='housedetail',
            new_name='detail',
        ),
    ]
