# Generated by Django 3.1.5 on 2021-12-05 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0011_auto_20211205_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerformfill',
            name='detail',
        ),
    ]
