# Generated by Django 3.1.5 on 2021-12-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0012_remove_ownerformfill_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerformfill',
            name='allinfo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
