# Generated by Django 3.1.5 on 2021-12-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0013_ownerformfill_allinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='ownerformfill',
            name='division',
            field=models.CharField(max_length=50),
        ),
    ]
