# Generated by Django 3.1.5 on 2021-12-21 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0015_auto_20211221_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownerformfill',
            old_name='location',
            new_name='loc',
        ),
    ]
