# Generated by Django 3.1.5 on 2022-01-23 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0016_auto_20211221_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('review', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mainkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final.ownerformfill')),
            ],
        ),
    ]
