# Generated by Django 3.1.5 on 2022-01-28 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0017_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='r',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('reeview', models.CharField(max_length=500)),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final.ownerformfill')),
            ],
        ),
    ]
