# Generated by Django 3.1.5 on 2022-01-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0019_auto_20220128_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r',
            name='rate',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='rating',
            name='review',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
