# Generated by Django 3.1.5 on 2022-02-01 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0020_auto_20220129_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='houserate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_review', models.TextField()),
                ('info_rate', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=100)),
                ('infor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final.ownerformfill')),
            ],
        ),
    ]
