# Generated by Django 3.1.5 on 2022-02-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0021_houserate'),
    ]

    operations = [
        migrations.CreateModel(
            name='measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='rating',
        ),
    ]
