# Generated by Django 3.1.5 on 2022-02-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0023_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=100)),
            ],
        ),
    ]
