# Generated by Django 3.1.5 on 2022-02-11 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0024_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='Location',
            new_name='location',
        ),
    ]
