# Generated by Django 3.1.5 on 2022-02-11 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0025_auto_20220211_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='ownername',
        ),
    ]
