# Generated by Django 3.1.5 on 2022-02-11 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0026_auto_20220211_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='ownername',
            new_name='name',
        ),
    ]
