# Generated by Django 3.1.5 on 2022-02-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0027_auto_20220211_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerformfill',
            name='houserent',
            field=models.IntegerField(max_length=100),
        ),
        migrations.DeleteModel(
            name='r',
        ),
    ]
