# Generated by Django 3.1.5 on 2022-02-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0029_auto_20220220_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerformfill',
            name='houserent',
            field=models.IntegerField(),
        ),
    ]
