# Generated by Django 3.1.5 on 2022-02-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0030_auto_20220220_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerformfill',
            name='houserent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
