# Generated by Django 3.1.5 on 2022-02-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0032_searchautotry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='searchautotry',
        ),
        migrations.AlterField(
            model_name='ownerformfill',
            name='housesize',
            field=models.IntegerField(max_length=100),
        ),
    ]
